# Generated by Django 4.2.4 on 2023-08-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='men.category'),
        ),
        migrations.AlterField(
            model_name='men',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='men',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='men',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='men',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='men',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
